// Generated by CoffeeScript 1.7.1
(function($) {
  $.fn.pullQuote = function(opts) {
    opts = $.extend({}, $.fn.pullQuote.options, opts);
    return this.each(function() {
      var elem, newElem, text;
      elem = $(this);
      text = elem.text();
      return newElem = $("<" + opts.outputElem + "/>", {
        "class": opts.outputClass,
        text: text
      }).insertAfter(opts.insertAfter);
    });
  };
  return $.fn.pullQuote.options = {
    outputClass: "pullquote",
    outputElem: "blockquote",
    insertAfter: "elem"
  };
})(jQuery);
